events {

}

http{
    upstream backend{
        server apigatway:8000;
        server apigateway:8000;
    }
    server{
        listen 8000;
        location /{
            porxy_pass https:backend;
        }
    }
}